### PR TITLE
Feature/googlelogin

### LINKED ISSUE #21: JWT token refresh
Currently, the refresh of the JWT token has not yet been implemented. once the session expired, we need to authenticate again with google.

### PR DESCRIPTION
**Pull request by ChristofferNissen**
Authentication is now implemented. 

Authorization is done with google on frontend through React Hooks, the frontend then sends the token to the backend for signing, and the signed version gets returned to the frontend for future communication. 

All endpoints except /auth is now secured. 

I removed the two different authentication schemes. If you want that feature, you can enable it again, but CORS was giving me huge problems so to simplify the setup i removed the, to me, unneccesary overhead. Let me know if this is important.

### CODE REVIEW

**Comment by ChristofferNissen** [comment]
Requires two env files in frontend folder:

.env.local
REACT_APP_GOOGLEKEY=20840044614-h4k2pdffbgumpqvri0g1sv5mn4q61q71.apps.googleusercontent.com
REACT_APP_URL=http://localhost:8080/google

.env.production
REACT_APP_GOOGLEKEY=20840044614-h4k2pdffbgumpqvri0g1sv5mn4q61q71.apps.googleusercontent.com
REACT_APP_URL=https://sonar-survey-rioz6g7rrq-lz.a.run.app/google

**Comment by ChristofferNissen** [comment]
The two files could potentially be added to git since both are urls and can easly be found in the app anyway. 

Secure vars will be set on docker containers from CI

**Comment by ChristofferNissen** [comment]
# Evaluation steps

## 1 Create .env.local and .env.production

in sonar-view/frontend/

.env.local

```
REACT_APP_GOOGLEKEY=20840044614-h4k2pdffbgumpqvri0g1sv5mn4q61q71.apps.googleusercontent.com
REACT_APP_URL=http://localhost:8080/google
```

.env.production
```
REACT_APP_GOOGLEKEY=20840044614-h4k2pdffbgumpqvri0g1sv5mn4q61q71.apps.googleusercontent.com
REACT_APP_URL=https://sonar-survey-rioz6g7rrq-lz.a.run.app/google
```

Production is run when .env.local is not present

## 2 Build

from sonar-view/

```
docker-compose build
```

## 3 Deploy

```
docker-compose up
```

## 4 Open localhost:3000
Login
* Try another google account than your eficode
* Try your eficode account

Logout

**Comment by sofusalbertsen** [comment]
Screenshot from 2020-11-26 07-58-30
For some odd reason, I do not get a page when doing the steps you have instructed above.
What am I doing wrong?
`npm instal` and `npm run dev` gives the same 404 fault.
@ChristofferNissen

**Comment by ChristofferNissen** [comment]
Hmm, thats unfortunate. I think its due to the user role not being set on the very first load. I think it might have just used old values in my testing. 

Can you run (in the console in browser)

```
localStorage.setItem("user_role", "guest")
```

Then you should be shown the login page. If this works, i might have a new fix up soon

**Comment by sofusalbertsen** [comment]
Works like a charm! :tada: :t-rex: :tada:

**Pull request merged**
